#server.port: 3505
server.port: 8080
server.address: 0.0.0.0
# http.port: 8082

#ssl
# manual https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.configure-ssl
# https://www.baeldung.com/spring-boot-https-self-signed-certificate
# https://www.codejava.net/frameworks/spring-boot/configure-https-with-self-signed-certificate
# https://www.baeldung.com/linux/add-self-signed-certificate-trusted-list
# https://dml.compkaluga.ru/forum/index.php?showtopic=106739

# ssl context
#server.ssl.enabled: false
#server.ssl.key-store-type: PKCS12
#server.ssl.key-store: ./certs/localhost.p12
#server.ssl.key-store-password: 123456
#server.ssl.certificate: /home/alekcei/keystore/fullchain.pem
#server.ssl.certificate-private-key: /home/alekcei/keystore/privkey.pem

webdav.cors.origins: '*'
#webdav.cors: http://localhost:4200"
logging.access.name: './access.log'

####  STATIC webdav  ####
#webdav.folder.path: '/home/alekcei/webdav'

#webdav.folders[0].path: '/home/alekcei/webdav'
#webdav.folders[0].login: ivanov
#webdav.folders[0].password: 123456
#
#


webdav.folder.path: /home/alekcei

